"""Build the bundled A/B library from checked-in structured card data.

Chinese titles and rules are independent summaries of game mechanics, not scans
or official translated card text. Source links are stored on each card.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def main():
    cards = json.loads((ROOT / 'data/original-cards.json').read_text())
    expected = [f'{deck}{n:03d}' for deck in 'AB' for n in range(1, 169)]
    assert [c['id'] for c in cards] == expected, 'Missing or duplicated cards'
    for c in cards:
        assert all(c.get(k) for k in ('name', 'nameEn', 'effect', 'requirement', 'url'))
        assert c['kind'] == ('minor' if int(c['id'][1:]) <= 84 else 'occupation')
        # Official A-D deck structure: 085–126 = 1+, 127–147 = 3+, 148–168 = 4+.
        if c['kind'] == 'occupation':
            n = int(c['id'][1:])
            assert c['minPlayers'] == (1 if n <= 126 else 3 if n <= 147 else 4), c['id']
        assert isinstance(c['points'], int) and c['costs']
        assert all(n >= 0 for cost in c['costs'] for n in cost.values())
    (ROOT / 'card-catalog.js').write_text('// Generated by scripts/import_catalog.py; edit data/original-cards.json.\nwindow.ORIGINAL_CARD_CATALOG = ' + json.dumps(cards, ensure_ascii=False, separators=(',', ':')) + ';\n')
    print(f'Built {len(cards)} cards (168 occupations, 168 minor improvements)')

if __name__ == '__main__':
    main()
